### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by anbuharry** [wxjiao/ResNet-Video-Features#1]
Hello @wxjiao 

Could you please tell me how to extract frames from  Multi-video and stored them in one folder

**Comment by wxjiao** [comment]
> Hello @wxjiao
> 
> Thanks for uploaded this code is very useful for my project. Could you please tell me how can extract frames from a video and stored them in one folder with a sequence of number

**Comment by wxjiao** [comment]
Sorry, I don't get your question. 
FFmpeg can do what you want, which I already explained in the README of this repo.
You may take a look at the FFmpeg software.
Thx.

**Comment by anbuharry** [comment]
> Sorry, I don't get your question.
> FFmpeg can do what you want, which I already explained in the README of this repo.
> You may take a look at the FFmpeg software.
> Thx.

Thanks for the reply @wxjiao 

My question is I try to extract feature from multi videos and frames are stored in different folders, how can I make them in one folder

**Comment by wxjiao** [comment]
Sorry, I haven't tried that. But maybe you can concatenate your videos first into a unified one and then extract frames from it. Just a guess.

**Comment by anbuharry** [comment]
> Sorry, I haven't tried that. But maybe you can concatenate your videos first into a unified one and then extract frames from it. Just a guess.

@wxjiao  Thank you
