### ISSUE TITLE
Feature extraction strarting issue

### ISSUE THREAD

**Issue by Chuttyboy** [wxjiao/ResNet-Video-Features#2]
Hai @wxjiao @yuewang-cuhk 

While extracting features from video numbers starting with 1 , but i want to start with 0 how can I do that?

**Comment by wxjiao** [comment]
> Hai @wxjiao @yuewang-cuhk
> 
> While extracting features from video numbers starting with 1 , but i want to start with 0 how can I do that?

You may modify the video numbers at first before executing the script, which should be the easiest way without modifying the script.

**Comment by Chuttyboy** [comment]
> > Hai @wxjiao @yuewang-cuhk
> > While extracting features from video numbers starting with 1 , but i want to start with 0 how can I do that?
> 
> You may modify the video numbers at first before executing the script, which should be the easiest way without modifying the script.

@wxjiao 

video number doesn't matter, I expect to start frames number starts with 0.jpg, 1.jpg like this 

Thank you

**Comment by Chuttyboy** [comment]
Hai @wxjiao 

![Screenshot from 2021-08-11 10-30-24](https://user-images.githubusercontent.com/79959547/128972139-6035e914-9af3-4334-b8c8-14380c0e2055.png)

Here frame numbers start with 1.jpg but I expect to start with 0.jpg, where do I need to change?

Thank you

**Comment by wxjiao** [comment]
> Hai @wxjiao
> 
> ![Screenshot from 2021-08-11 10-30-24](https://user-images.githubusercontent.com/79959547/128972139-6035e914-9af3-4334-b8c8-14380c0e2055.png)
> 
> Here frame numbers start with 1.jpg but I expect to start with 0.jpg, where do I need to change?
> 
> Thank you

Hi, that just happens to be the default starting index for frame sequence output in *ffmpeg*. 
You can override it by adding "-start_number 0". Please find the solution here: https://stackoverflow.com/questions/60044089/why-does-ffmpeg-output-frames-starting-with-0001-instead-of-0000
